### ISSUE TITLE
Small laggs with Addon enables

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion.kodi#1] opened 2014-03-15 00:02 UTC
Hi,
im using this addon combined with Hyperion for a long time now. Its working pretty nice, but i always noticed some small laggs and i was wondering if my eyes are crossed or the movie really laggs. So today i found some things out:
I watched the end of Batman Dark Knight, and there you could see the laggs pretty good. (i mean the part with the text, the credits). The movie is in 1080p. I tried using Full Screen mode and this full Screen Windows mode.
The Full Windows mode is actually a stuttering for some time, and then fluent again. (ca 3-5 sek each).
The Full Screen mode is more are little lagg after some time (3-5sek here too). So the credits moved up a little bit more than normal.
I was wondering if my PC is too slow, xbmc or the hdd. My PC is an i5 with an ssd and all that stuff. Shouldnt be the Problem. I also played the Video with VLC Player in Full Screen. No Problem. So the HDD via usb3 should work fine. I tried disabling the addon and voila! Video is fluent. Enabled.. Video is laggy :(((

Is there a tip, a solution you can provide to fix this? Did you ever notic this? You have to look from far away i would say. Im using the newest 12.x XBMC, i think its called Frodo and the newest Hyperion addon (i think there is only 1.0.0) and the newest Raspberry build. Please help :)

**Comment by poljvd** [comment] 2014-03-17 10:14
To be short: When you enable the Hyperion XBMC addon, the video is laggy (not hyperion). And when you disable the addon all is oke?

I don't have this experience (Gigabyte Brix i5 running Ubuntu + XBMC 13). Do you run Hyperion on a RPi or also on your PC? Is your PC running Windows or Linux? 

I will have a look at the code to see if I can find a possible reason...

Have you ever tried the Boblight addon? It does more or less the same and uses the same functions. If that would run smoothly then I have a reference to check the code against

**Comment by NicoHood** [comment] 2014-03-17 10:38
Im running XBMC 12.x on my PC. via lan its sending the data to the raspberry Pi. with a switch in between
Im using Win7. I also reinstalled XBMC completly. I dont have any other addons or skins. Just blanko xbmc with my movie library. if the addon is enabled it laggs, as i described

if you need any more infos, just ask :)

**Comment by NicoHood** [comment] 2014-03-17 21:37
Okay today i found some new things out:
This bug happens as described in Batman Dark Knight but NOT in Spiderman.
And I also started Batman with VLC again. This seems to be a problem with xbmc+ hyperion
Well its not the characters, i think its something with the codecs :D 
Can you somehow pm me, so i can provide you the information you need to analyze this? I dont want to post everything here

**Comment by NicoHood** [comment] 2014-03-19 22:11
Okay, today i started watching Dark Knight Rise and the laggs were totally not acceptable. So I played around with this and found a solution:
The video runs in true Full Screen and I turned OFF vertical synch or something like that. So it seems to work for now.
Just so i can understand: Why does this happen? Do you have any explanation? Is there a way to fix this via this addon or is my PC/Graphicscard just crap? Maybe you could provide this Information in the readme, so other people know what to do. Please answer

Thanks
Nico :)

**Comment by poljvd** [comment] 2014-03-20 15:52
I don't have an answer why vertical sync would be an issue.

It will probably have something to do with the capture interface exposed by XBMC which does not work efficiently with vertical sync on. This behavior will also be dependent on the platform (Windows/Linux) you have, because another low level player may be used by XBMC. At this moment I just know too little about what is causing this to write some rules for this so I won't do that at the moment, but I will keep this issue in mind when someone has similar problems.

Thank you for your feedback.

**Comment by mettmaniac** [comment] 2014-07-10 14:15
Hi, I am facing the same problem on a Windows 7 machine running XBMC.
When the Hyperion plugin is running and connected to the raspberry pi, the video starts to stutter.
I can easily reproduce by just unplugging the raspberry during the video and the stuttering vanishes.

Let me know if you need any additional information - I would love to get this fixed.
I will also play around a bit with setting in the Hyperion config, maybe it is an issue with the baud rate or the frequency of checks etc...

Thanks for your help and thanks for Hyperion - really amazing tool :)

**Comment by poljvd** [comment] 2014-07-11 10:43
When you unplug the RPi, the connection to Hyperion fails and the plugin will stop grabbing. It is this grabbing which is causing the issues. I am afraid that the issue is caused by the Capture interface of XBMC which performs different based on XBMC video settings. According to NicoHood switching the vertical sync off makes a difference, but I assume you already you tried this.

**Comment by NicoHood** [comment] 2014-07-11 10:48
I want to note that it was different from movie to movie. And it also mattered if you start xbmc in true fullscreen or in a fullscreen window. And maybe my graphic card is too slow for this operation but it seems he has the same problem. Playing a bit with the settings made it work for me.

I just want to note something about general graphic card problems: For me it was impossible to start programs in fullscreen in fullhd untin i set it to 50hz. I have NO idea why that happens. I also can play portal 2 and other games with full fps with highest settings. And games like payday 2 just wont work in fullhd no matter how low all settings are. Playing in hd ready works fine. But maybe thats not a problem with xbmc, it also shouldnt take that much gpu because its a prerendered movie?

happy trying

**Comment by brindosch** [comment] 2016-04-18 09:30
I will close this issue due to age. You could open a new issue with new symptoms. and due to the point that poljvd found nothing that could be fixed 2 years before.
Also it seams that is (was) a kodi problem.

**Closed as completed by brindosch** 2016-04-18 09:30 UTC
