### ISSUE TITLE
Settings / Out Of Sync / Update Problems >:(

### ISSUE THREAD

**Issue by blistex** [hyperion-project/hyperion.kodi#28] opened 2016-09-25 17:39 UTC
Hi guys,

I have some pretty annoying problems which are getting on my nerves and ruining my experience.

My Setup:

Client: NVIDIA Shield TV (FW:3.1) running SPMC newest version.
Master: Raspberry Pi 2 with Raspbian

My Settings:

Grabber picture width (pixel) 256
Grabber picture height (pixel) 192
Frame rate (fps) 60
1. Out Of Sync
   I have the Setting in SPMC Adjust display refresh rate at on (more specific It says Always).
   (Settings>Video>Playback>Adjust display refresh rate)

Most movies playback at 24fps/24Hz our European plays at 25fps/50Hz and then some other content I have playback at 30fps/60Hz! And I wanna keep that setting on because otherwise I see stutters.

With my current settings playing 24fps/24Hz content causes the LED's to be out of sync! If I use the Standard Setting Frame rate (fps) 10 24fps/24Hz is fine but then on other content the LED's are not moving fluid...

How can I achieve that the plugin notices the change in fps/Hz?

Turning Adjust display refresh rate on or off at the Master (RasPi) didn't solve this issue either.

I don't know what to do anymore. Help please.
1. Settings

I couldn't find a place where the Settings Menu of this Plugin was explained!

I don't know if I did the Settings right or wrong! because they are not explained.

The NVIDIA Shield is extremely powerful as you may know if you are familiar with it. Therefore I can crank up the pixel count and it won't slow down. But what is the right Setting for me? Does (pixel) mean the amount of the LED's I have? Do I have to input the amount of Led's I have in there? What about fps? Can someone please explain it to me? I want the best/precise outcome possible. Can someone tell me their Settings just to compare?
1. Update Problems

Right now the newest version is 1.0.3 I believe. After updating it says failed... does anyone else experience this?

**Comment by hyperops** [comment] 2016-09-28 18:16
Hi . Jep i also get an error when installting the Kodi Addon.

exceptions.AttributeError

20:00:53 T:1453885744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/addon.py", line 36, in <module>
                                                from state import DisconnectedState 
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/resources/lib/state.py", line 27, in <module>
                                                from hyperion.Hyperion import Hyperion
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/resources/lib/hyperion/Hyperion.py", line 28, in <module>
                                                from message_pb2 import HyperionRequest
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/resources/lib/hyperion/message_pb2.py", line 6, in <module>
                                                from google.protobuf import descriptor as _descriptor
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.protobuf/lib/google/__init__.py", line 2, in <module>
                                                __import__('pkg_resources').declare_namespace(__name__)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--

**Comment by brindosch** [comment] 2016-09-30 13:02
Greetings,
i never tested 24hz playback so no idea yet. Are you using smoothing? Without - 10 pictures each second stutter indeed.
I have no insight about the framerate handling between the api we use and the video player. Maybe @WoLpH :)

The settings are explained at the wiki, but this might not fix your issue.
https://hyperion-project.org/wiki/Kodi-Addon

**Comment by wolph** [comment] 2016-09-30 13:22
The current system simply uses the configurable framerate setting which is probably not the best solution for this since framerates can vary. (code: https://github.com/hyperion-project/hyperion.kodi/blob/master/resources/lib/state.py#L151)
I'm not entirely sure if we can easily detect the framerate from Kodi but I'm sure it has to be possible so I'll try to incorporate that into the next fix. I'll change it into a maximum framerate at that point which will result in a 24fps if the max is 30 and 12 fps if you have the max set to 23 or something. Interpolating between frames won't result in anything good so it's better to rely on smoothing if your system can't handle the 24fps.

As for the resolution, that's the resolution of the image that's captured from Kodi. Larger is obviously heavier to do but I would recommend setting it at least to the amount of pixels you have in that direction. So if you have 200 leds horizontally it should be at least 200 pixels for all leds to get a distinct signal. 

I'd have to investigate the performance overhead of that method as well though. It might be better to simply keep it at 960x540 (half of 1920x1080) since that makes the interpolation much simpler.

**Comment by RickDB** [comment] 2016-12-16 16:15
Fixed in next release for Kodi 17, changes are already made to improve this and added configure-able delays per refresh rate if needed to fit all scenario's :)
Can check full overview here:

https://github.com/hyperion-project/hyperion.kodi/pull/31

Old method with fixed refresh rate just didn't make a whole of sense anymore and this way you don't need to worry about your content type / refresh rate as it will auto-detect it and adjust accordingly.

**Comment by blistex** [comment] 2017-05-09 18:49
Has this next version you talked about with those fixes been released?

**Comment by wolph** [comment] 2017-05-09 18:51
Not yet it seems, I've just pinged one of the devs to request a merge :)

**Comment by blistex** [comment] 2017-05-09 18:55
Thank you! you know i've been waiting for a long time and those issues are really annoying.

**Comment by blistex** [comment] 2017-05-13 23:15
Saw the Add On has been updated! So I installed it full of expectations and happiness only to find out that now with this version I have to choose between ambilight working with stuttery playback or no ambilight but smooth playback.... probably because hardware acceleration - MediaCodec (Surface) is off :( 

anyone else experiencing the same issue? still running NVIDIA Shield TV (FW:3.1) running Kodi 17.1

**Comment by wolph** [comment] 2017-05-13 23:27
You could try playing around with the delay setting, it's the most likely cause for this problem

**Comment by blistex** [comment] 2017-05-13 23:30
Any Suggestion what I should do with it? like turn off always use default delay or something?

**Comment by wolph** [comment] 2017-05-13 23:44
Yes, that could help. I personally don't have any similar hardware to test it on so I can't provide much detail here :(

**Comment by blistex** [comment] 2017-05-13 23:59
This version is pretty much useless for Android devices.... had my hopes up and the disappointment is accordingly big.... doesn't work on previous versions of kodi/spmc doesn't auto detect framerate have to input delay myself? obviously couldn't test ist but still. That was something I was looking for.

**Comment by RickDB** [comment] 2017-05-14 08:52
Tested under Linux and Windows here without issues with Kodi 17.* , Android is a mixed bag and under my Mi box it works only if I use software decoding as the hardware decoders aren't properly exposed by Kodi so pretty useless as 4K stutters like crazy.
Not much we can do about that sadly but there's some progress here:

https://hyperion-project.org/threads/android-grabber-app.76

**Comment by blistex** [comment] 2017-05-14 12:22
Yes it's a issue with Android. I tested it on Mac and it worked properly. But the Nvidia Shield TV is such a great device for kodi that I don't understand why there is no proper support. Android is not a small platform! many devices run it and more and more will in the future.

I also don't get why they break things with updates! kodi 16.* with hardware acceleration - MediaCodec (Surface) off worked just fine. With kodi 17.* it's broken.

It's easy for my to complain but I don't get why this can't grab with hardware acceleration on and if it really was necessary to only support kodi 17 and up!

anyway I will check out that thread you linked maybe there is a solution.

**Comment by RickDB** [comment] 2017-05-14 21:49
Will see if we can make a separate version for now that supports Kodi 16, should be only a few extra checks and a bit of extra overhead but nothing too serious :)

**Comment by RickDB** [comment] 2017-05-14 21:55
Restored the Kodi checks but you still get the benefits of the current release (per refresh configureable delay etc..):

[Hyperion addon - KODI 16 ONLY](https://github.com/hyperion-project/hyperion.kodi/files/999751/hyperion-kodi_withKodi16Compat.zip)

**Comment by blistex** [comment] 2017-05-17 19:02
Thank you for making a separate version that's compatible with kodi 16.* I tried installing it today but it fails every time! tried SPMC and the last kodi 16.* release...

**Comment by RickDB** [comment] 2017-05-19 08:32
Sorry about that, seems we had to change a few things for Kodi (protobuf dep) which on fresh installs will break.
Recommend setting both grabber height and width to 64 as that works best, new build below and tested on fresh Kodi install this time:

[hyperion.kodi-1.0.2.zip](https://github.com/hyperion-project/hyperion.kodi/files/1013592/hyperion.kodi-1.0.2.zip)

Just let me know how it goes as I will commit changes if this work correctly for inclusion in next official build.

**Comment by brindosch** [comment] 2017-05-19 09:27
Thank you Rick.
As far i know if you install a plugin by hand (zip) it doesn't download the dep packages. So it will most likely fail by design.

A problem we have now about this kodi 16 thing. We can't publish an addon to Kodi 16 anymore. Maybe we get a exception if we push 17 to. (No...)

**Comment by RickDB** [comment] 2017-05-19 12:12
Ah that explains it :)

We could post a separate version for legacy users outside of Kodi repo and if this solved it put that in separate git branch if we ever need to rebuild it, for Kodi 17 and up we can use master branch and publish to Kodi repo if they approve it ofc as I recall us having some issues with protobuf which was blocking that process.

Kodi 17 is such a vast improvement people will most likely be upgrading to it as well.

**Comment by brindosch** [comment] 2017-05-19 12:53
> with protobuf which was blocking that process.

Yes, it was just about using it (protobuf) as dependency. Which is already fulfilled :)
Yes, i think it is just a matter of time.

**Comment by blistex** [comment] 2017-05-20 12:36
@RickDB 

it let's me install it now but it doesn't work. Tried in on the Shield with my SPMC Setup and a clean new install an my phone. Both times a popup show saying Error please checkt out the Log. If anyone can tell me where to find that log I could post it here.

**Comment by RickDB** [comment] 2017-05-23 13:14
SPMC should have a log upload function :)

https://github.com/koying/SPMC/wiki/How-do-I-publish-a-debug-log%3F

**Comment by blistex** [comment] 2017-05-24 16:40
http://paste.semperpax.com/pioeavlzv

this is the log from a clean install on my phone.

**Closed as completed** 2023-07-11 19:45 UTC
