### ISSUE TITLE
1.0.6 fails to start

### ISSUE THREAD

**Issue by FPA-ChrisLaird** [hyperion-project/hyperion.kodi#50] opened 2023-08-18 13:26 UTC
1.0.6 fails to start for me.

ModuleNotFoundError: No module named 'PIL'

Running Kodi 20 on NVIDIA shield.

**Comment by Lord-Grey** [comment] 2023-08-18 15:40
@sanzoghenzo Should we fall back to just array transformation

```
            # retrieve image data and reformat into rgb format
            if self.__capture.getImageFormat() == 'BGRA':
                del self.__data[3::4]
                self.__data[0::3], self.__data[2::3] = self.__data[2::3], self.__data[0::3]
```

rather than using Image from PIL [here](https://github.com/hyperion-project/hyperion.kodi/blob/bd6aaab1d094bf157bdf38cedf1d7706d3eba80a/resources/lib/monitor.py#L128)?
Or is there a better way to ensure the availability of PIL?

**Comment by sanzoghenzo** [comment] 2023-08-18 16:16
If I understood correctly, pil library should be installed and available in kodi android version, at least on matrix... Maybe they changed things with nexus?
I'll try it on one of my android devices to see if I can reproduce this.

**Comment by Lord-Grey** [comment] 2023-08-18 18:14
@sanzoghenzo You can load the latest development code via a package from [my repository](https://github.com/Lord-Grey/hyperion.kodi/releases/tag/v20.0.1).
A side effect of testing the github action release capability.... :)

I will wait with the latest PR, in case something needs to be included.
Then we can publish a new version to Kodi, as protobuf was merged today, too.

**Comment by sanzoghenzo** [comment] 2023-08-19 18:57
FYI: Before getting my hands dirty with kodi android, I tested to see if the pil import was worth it by profiling the two conversion function, and PIL is indeed an order of magnitude faster.

So it's worth investingating what's going on on Android based devices (I'm making this assumption because I see that nvidia Shields run an android OS, @ChrisLaird am I right?)

**Comment by FPA-ChrisLaird** [comment] 2023-08-20 02:22
> FYI: Before getting my hands dirty with kodi android, I tested to see if the pil import was worth it by profiling the two conversion function, and PIL is indeed an order of magnitude faster.
> 
> So it's worth investingating what's going on on Android based devices (I'm making this assumption because I see that nvidia Shields run an android OS, @ChrisLaird am I right?)

You are correct. Thanks for investigating this. 
Let me know if you need any testing/info.

**Comment by sanzoghenzo** [comment] 2023-08-20 10:02
[As per this comment](https://github.com/xbmc/xbmc/issues/21531#issuecomment-1685238156), we sould only need to declare the pil dependency in the addon manifest.

I have some troubles with my android devices, so I could not fully test it, but at least it installs ok on my smarphone.

@Lord-Grey  On which fork/branch do you want me to set the PR?

**Comment by sanzoghenzo** [comment] 2023-08-20 10:03
@ChrisLaird  in the meantime, would you be so kind to test if this version works for you?

[script.service.hyperion-20.0.1.zip](https://github.com/hyperion-project/hyperion.kodi/files/12387890/script.service.hyperion-20.0.1.zip)

**Comment by Lord-Grey** [comment] 2023-08-20 11:20
> On which fork/branch do you want me to set the PR?

@sanzoghenzo It would be great, if you add changes [Here](https://github.com/Lord-Grey/hyperion.kodi/tree/Support_for_PR)

**Comment by FPA-ChrisLaird** [comment] 2023-08-21 08:14
> @ChrisLaird in the meantime, would you be so kind to test if this version works for you?
> 
> [script.service.hyperion-20.0.1.zip](https://github.com/hyperion-project/hyperion.kodi/files/12387890/script.service.hyperion-20.0.1.zip)

Hi again. On first installing it everything seemed to lagout.  Playing a video via Kodi resulted in no sound for some reason.  I've never seen this before.
Hyperion was working though.

I had to reboot the shield.

After reboot I disabled then enabled it again at which point it sat unresponsive for about 20s until coming to life again. However now Hyperion isn't working for some reason. Kodi also plays videos with sound again.
I don't see the Hyperion Kodi service erroring out enabling it.
All settings are defaults,.except for the IP address of course.

**Comment by FPA-ChrisLaird** [comment] 2023-08-21 08:46
I uninstalled and reinstalled the add-on and it didn't change anything. Still doesn't appear to capture anything. I do have Hyperion Kodi control plugin too so disabled it, but no difference.

Finally I ran the Hyperion grabber app and that does capture as expected. 

So it seemed to work initially, one time, but never again lol.

**Comment by sanzoghenzo** [comment] 2023-08-22 22:05
I finally found the problem: no image is captured, the debug log shows many "CRenderManager::Capture - unknown capture id: 1".

After some research I [found a workaround](https://forum.kodi.tv/showthread.php?tid=369869&pid=3113910#pid3113910): 
- Settings -> Player 
- Check Allow Hardware Acceleration MediaCodec (Surface)
- Uncheck Allow Hardware Acceleration MediaCodec

Not sure if we can do something about it in the code!

In the meantime, I've done some refactoring, I'll do a PR ASAP.

**Comment by FPA-ChrisLaird** [comment] 2023-08-22 23:14
Awesome will retest tonight.

**Comment by FPA-ChrisLaird** [comment] 2023-08-23 22:08
@sanzoghenzo I tried it last night with the kodi settinngs you describe above.  It appeared to work initially but on closing/reopening kodi it didn't auto start.
Rebooting didn't help either.  So I don't think its 100% fixed yet?

**Comment by sanzoghenzo** [comment] 2023-08-23 22:15
Hi @ChrisLaird,
Can you please enable kodi debug log (from the kodi logging settings) and post here the contents of the log file (the path should be visible on tje osd)?
That way I can avoid the guessing game and be quicker to get the cause of the problem 😉

**Comment by FPA-ChrisLaird** [comment] 2023-08-24 11:28
@sanzoghenzo 
I get a bunch of these log entries.

`2023-08-24 23:08:22.772 T:6596    debug <general>: [Hyperion Ambilight] - Establishing connection to hyperion
2023-08-24 23:08:22.874 T:6596    debug <general>: [Hyperion Ambilight] - Captured image is none or < expected. captured: 0, expected: 16384`

**Comment by FPA-ChrisLaird** [comment] 2023-08-24 11:42
A bit more info.  I tried adjusting the hardware acceleration settings a bit.
1) MediaCodec (Surface)  = On. Doesn't work, as above.

2) MediaCodec = On. Actually does work, but kills video rendering performance, audio goes way out of sync.  I do see Hyperion output but it's super choppy.

3) No hardware acceleration. Very similar to case 2.

Testing performed with add-on v20.0.1

**Comment by sanzoghenzo** [comment] 2023-08-24 11:55
I suppose that near the logs you posted there's the line `CRenderManager::Capture - unknown capture id: X`, isn't it?
(Pardon me if I sound harsh, but when somebody asks you for the log, provide the entire log! Only that way we can have the entire picture and help you troublershooting...)

Unfortunately there's no solution for this, see [this explanation](https://forum.kodi.tv/showthread.php?tid=369869&pid=3122893#pid3122893).
You either have to disable hardware acceleration or move to a linux box, I suppose.

**Comment by FPA-ChrisLaird** [comment] 2023-08-24 21:32
> I suppose that near the logs you posted there's the line `CRenderManager::Capture - unknown capture id: X`, isn't it? 

Yeah, there are many.
`error <general>: CRenderManager::Capture - unknown capture id: 3`

**Closed as completed** 2024-05-04 18:25 UTC
Labels: Not a Hyperion issue
